version: '3.2'

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./timescale/data
        target: /var/lib/postgresql/data
    environment: 
        POSTGRES_PASSWORD: password